線分ABと点Cの距離を求める関数追加
SSL-Roots/robocup_scenario_test pull request #19
Opened 2024-03-28 14:15 UTC by nabekuro0104

2024-03-30 06:13 UTC, ShotaAk commented
コミットログは英語にしたいのでタイトル変更しました

2024-03-30 06:22 UTC, ShotaAk requested changes
体裁についてコメントしました〜

2024-03-30 06:22 UTC, ShotaAk commented on rcst/calc.py
> +def calc_vector(x0, y0, x1, y1):
型ヒントをつけたいです。（多分こうかな？）
```suggestion
def calc_vector(x0: float, y0: float, x1: float, y1: float) -> tuple[float, float]:
```

2024-03-30 06:22 UTC, ShotaAk commented on rcst/calc.py
> +    # ABが点 or 点CがA側
このパッケージは英語で頑張りたいです
```suggestion
    # AB is point or point C is A side
```

2024-03-30 06:22 UTC, ShotaAk commented on rcst/calc.py
> +    # 点CがB側
```suggestion
    # Point C is the B side
```

2024-03-30 06:22 UTC, ShotaAk commented on rcst/calc.py
> +def distance_point_c_to_line_ab(xa: float, ya: float, xb: float, yb: float, xc: float, yc: float) -> float:
関数名の順番に変数をセットしたいです。

```suggestion
def distance_line_ab_to_point_c(xa: float, ya: float, xb: float, yb: float, xc: float, yc: float) -> float:
```

2024-03-30 06:22 UTC, ShotaAk commented on tests/test_calc.py
> +    assert calc.distance_point_c_to_line_ab(0, 0, 1, 0, -1, 0) == 1
```suggestion
def test_distance_line_ab_to_point_c():
    assert calc.distance_line_ab_to_point_c(0, 0, 0, 1, 1, 0) == 1
    assert calc.distance_line_ab_to_point_c(0, 0, 2, 2, 1, 1) == 0
    assert round(calc.distance_line_ab_to_point_c(0, 0, 4, 2, 6, 3), 2) == 2.24
    assert calc.distance_line_ab_to_point_c(0, 0, 0, 0, 0, 1) == 1
    assert calc.distance_line_ab_to_point_c(0, 0, 1, 0, 2, 0) == 1
    assert calc.distance_line_ab_to_point_c(0, 0, 1, 0, -1, 0) == 1
```

2024-04-02 14:13 UTC, nabekuro0104 commented
@ShotaAk 更新しました〜

2024-04-02 14:15 UTC, ShotaAk approved these changes
LGTM！

2024-04-02 14:15 UTC, merged